### ISSUE TITLE
worker.stop() throws tooz exceptions when using tooz advertiser

### ISSUE THREAD

**Issue by jimbobhickville** [ToolsForHumans/zag#15]
When you stop a worker, it doesn't clean up tooz properly and it throws a connection error because the zookeeper connection is shut down and then it tries to remove the group. Pretty sure it's just an order of shutdown problem.

**Comment by jimbobhickville** [comment]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/gunicorn/reloader.py", line 55, in run
    self._callback(filename)
  File "/Users/gnhill/code/liquidweb/mwxapi/mwxapi/operations/worker.py", line 80, in source_changed
    log.error("Failed to stop worker cleanly", exc_info=exc)
ValueError: execv() arg 2 must not be empty

[2018-11-07 14:59:29 -0600] [70585] [INFO] [mwxapi.operations.worker] Stopping worker
Traceback (most recent call last):
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/tooz/drivers/zookeeper.py", line 258, in _leave_group_handler
    async_result.get(block=True, timeout=timeout)
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/kazoo/handlers/utils.py", line 73, in get
    raise self._exception
kazoo.exceptions.ConnectionClosedError: Connection has been closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gnhill/.virtualenvs/mwxapi/bin/mwxapi_worker", line 11, in <module>
    load_entry_point('mwxapi', 'console_scripts', 'mwxapi_worker')()
  File "/Users/gnhill/code/liquidweb/mwxapi/mwxapi/operations/worker.py", line 94, in run
    log.info('Stopping worker')
  File "/Users/gnhill/code/side-projects/zag/zag/engines/worker_based/worker.py", line 197, in stop
    advertiser.stop()
  File "/Users/gnhill/code/side-projects/zag/zag/engines/worker_based/types.py", line 460, in stop
    self.retract()
  File "/Users/gnhill/code/side-projects/zag/zag/engines/worker_based/types.py", line 439, in retract
    self._coordinator.leave_group(group_id).get()
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/tooz/drivers/zookeeper.py", line 544, in get
    return self._handler(self._kazoo_async_result, timeout, **self._kwargs)
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/tooz/drivers/zookeeper.py", line 268, in _leave_group_handler
    cause=e)
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/tooz/utils.py", line 225, in raise_with_cause
    excutils.raise_with_cause(exc_cls, message, *args, **kwargs)
  File "/Users/gnhill/.virtualenvs/mwxapi/lib/python3.7/site-packages/oslo_utils/excutils.py", line 143, in raise_with_cause
    six.raise_from(exc_cls(message, *args, **kwargs), kwargs.get('cause'))
  File "<string>", line 3, in raise_from
tooz.ToozError: Connection has been closed
```
